[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "beaker"
version = "0.0.2"
authors = [
    { name="Will Girten", email="will.girten@databricks.com" },
]
description = "Execute benchmark queries against a Databricks SQL warehouse or cluster."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "databricks-sql-connector",
    "pyspark",
    "pyodbc"
]

[project.urls]
"Homepage" = "https://github.com/goodwillpunning/beaker"
"Bug Tracker" = "https://github.com/goodwillpunning/beaker/issues"
